### ISSUE TITLE
Empty Schemas

### ISSUE THREAD

**Issue by amin-nejad** [kkirsche/apispec-pydantic-plugin#22]
The following code snippet:

```python
from apispec import APISpec
from apispec_pydantic_plugin import PydanticPlugin
from pydantic import BaseModel

# Define your Pydantic models
class Item(BaseModel):
    id: int
    name: str
    description: str | None = None

class Error(BaseModel):
    code: int
    message: str

# Create an APISpec instance with the Pydantic plugin
spec = APISpec(
    title="My API",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[PydanticPlugin()],
)

# Add your Pydantic models to the spec
spec.components.schema("Item", schema=Item)
spec.components.schema("Error", schema=Error)

# Generate the OpenAPI spec
spec_dict = spec.to_dict()
print(spec.to_yaml())
```

gives the following output:

```
paths: {}
info:
  title: My API
  version: 1.0.0
openapi: 3.0.2
components:
  schemas:
    Item: {}
    Error: {}
```

Not sure if I'm using the plugin incorrectly. How can I get the schema to populate with the arguments of the model?

Versions:

```
apispec==6.6.1
apispec-pydantic-plugin==0.5.2
pydantic==2.9.1
```

**Comment by kkirsche** [comment]
If you import `ApiBaseModel` from apispec-pydantic-plugin and have `Item` subclass that instead, the model will be registered with the plugin. I wasn't aware of a way to hook subclass definitions on a third party library, thus needed to have a subclass which is otherwise just pydantic's class. 

Hope that helps!

**Comment by amin-nejad** [comment]
Thanks for the speedy response! I'm afraid the output still remains the same even with that change

```python
from apispec import APISpec
from apispec_pydantic_plugin import PydanticPlugin, ApiBaseModel

# Define your Pydantic models
class Item(ApiBaseModel):
    id: int
    name: str
    description: str | None = None

class Error(ApiBaseModel):
    code: int
    message: str

# Create an APISpec instance with the Pydantic plugin
spec = APISpec(
    title="My API",
    version="1.0.0",
    openapi_version="3.0.2",
    plugins=[PydanticPlugin()],
)

# Add your Pydantic models to the spec
spec.components.schema("Item", schema=Item)
spec.components.schema("Error", schema=Error)

# Generate the OpenAPI spec
spec_dict = spec.to_dict()
print(spec.to_yaml())
```

**Comment by kkirsche** [comment]
I'd need to look at how I use it to answer. I was just scanning through the code for obvious items and that's what I saw. 

Once I'm in front of a machine where I can access an app using it, I'll be able to respond with a minimal functional example.

Thanks for your patience and sorry for the inconvenience

**Comment by kkirsche** [comment]
I found the bug. When adding models directly to the schema via `components.schema`, it changes how APISpec calls `schema_helper`. When defining the models only from within docstrings, it gets passed in under the "model" keyword while here it ends up coming in under "schema". I'll update this and publish it shortly with an added test to catch potential regressions in the future.

**Comment by kkirsche** [comment]
0.6.0 released with that fix. Please let me know if you run into any issues! Thanks for the report and sorry for the issue!

**Comment by amin-nejad** [comment]
Thanks very much @kkirsche!
